### ISSUE TITLE
模拟点击没用？？

### ISSUE THREAD

**Issue by Bahtya** [jxzhung/WxTiaoYiTiao#1]
我的一点确定，就自动把小程序分享给好友。。并没有模拟按压

**Comment by jxzhung** [comment]
可以开启开发者选项里面的显示“指针位置”查看模拟触摸的位置，实际上调用SU在底部模拟滑动了一段时间。你的情况应该是碰到左下角的分享按钮了。在com/jzhung/tiaoyitiaohelper/service/FloatViewService.java的onCreate中有一行mTouchPointLeftMargin = DensityUtil.dip2px(getApplicationContext(), 50); 可以把后面的50改大一点就行了。
